image: Ubuntu2004  # образ для сборки, Ubuntu1804

stack: node 20  # окружение

branches:
  only:
    - main  # ветка git

cache: node_modules  # кеширование

install:
  # Установка nvm (Node Version Manager)
  - ps: ". { iwr https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.ps1 }"
  # Установка требуемой версии Node.js
  - nvm install 20
  - nvm use 20
  - npm install
  - npm install -g push-dir

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

# test_script:
#   - npm run lint  # скрипт тестирования
  # - npm run lint && npm test  # скрипт тестирования

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose
